### ISSUE TITLE
Suggestion - Add tool to npm

### ISSUE THREAD

**Issue by joewood** [fivetran/typescript-closure-tools#3]
Add tool to npm and set-up a `bin` directory so that you can run it in the commandline from anywhere.

**Comment by trodi** [comment]
I see that this is now an npm package. Is there any reason this issue is still open? The only reason I could think of is that it would be great if the readme was updated to reflect this. Would save some people time.

**Comment by georgewfraser** [comment]
Updated readme with https://github.com/fivetran/typescript-closure-tools/commit/745e7590015accf041a5eb9cd7f3bc8995479d93
