### ISSUE TITLE
Update for TypeScript 1.4

### ISSUE THREAD

**Issue by alexeagle** [fivetran/typescript-closure-tools#5]
For example, TypeScript supports type unions now so they could be carried across from Closure.

(I've done similar stuff in the closure compiler, eg https://github.com/google/closure-compiler/commit/f82dd2f344ea7415d4cd466f065e22b596885eb7 )

**Comment by georgewfraser** [comment]
I might wait for intellij's plugin to catch up to typescript before doing this.

**Comment by alexeagle** [comment]
Newest WebStorm EAP has 1.4 support (but not yet complete)
https://youtrack.jetbrains.com/issue/WEB-14151#comment=27-924524

However, I've started trying to implement the closure source -> .d.ts pass inside the closure compiler instead. I'll update here if I get that working.

**Comment by mindplay-dk** [comment]
Looks like it no longer needs to expand unions into overloads?

**Comment by georgewfraser** [comment]
Indeed. I'm just super-busy and haven't gotten to this.

**Comment by georgewfraser** [comment]
Fixed
