### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by trodi** [fivetran/typescript-closure-tools#9]
The [npm package](https://www.npmjs.com/package/typescript-closure-tools) should be updated.

**Comment by trodi** [comment]
@georgewfraser there have been a number of improvements since the last package publish 11 months ago. It'd be great to see the package updated to avoid having to clone from the repo.

**Comment by georgewfraser** [comment]
Fixed

**Comment by trodi** [comment]
Thanks!
